version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "deps"
    groups:
      npm-patch-and-minor:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"

